# filepath: .streamlit/config.toml
[theme]
primaryColor="#008000"
backgroundColor="#F8F9FA"
secondaryBackgroundColor="#F0F2F6"
textColor="#0A0A0A"
font="sans serif"
[server]
runOnSave = true
[browser]
gatherUsageStats = false
